# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
  - https://cdn.bootcss.com/minireset.css/0.0.2/minireset.min.css
  - https://cdn.bootcss.com/highlight.js/9.15.9/styles/xcode.min.css
  - /styles/segment.css

# scripts loaded in the end of the body
scripts:
  -
